In [ ]:
from keras import backend as K 
from keras.preprocessing.image import ImageDataGenerator 
from keras.models import Sequential
from keras.models import Model 
from keras.layers import Conv2D, MaxPooling2D 
from keras.layers import Activation, Dropout, Flatten, Dense
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
from keras.applications import InceptionResNetV2 
! pip install split-folders
import tensorflow as tf
import split_folders
from keras import optimizers
from keras.preprocessing.image import ImageDataGenerator
from keras.applications import densenet
from keras.models import Sequential, Model, load_model
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense
from keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint, Callback
from keras import regularizers
from keras import backend as K
from keras import optimizers

In [ ]:
import numpy
import keras
import sklearn.metrics as metrics
img_width, img_height = 224, 224
batch_size = 8
epochs = 100
#path to test set0
val0_set_dir = "/content/drive/My Drive/validation /set0"

num_val0 = len(os.listdir(val0_set_dir))
print('1............',num_val0)

#path to load trained model 
model = keras.models.load_model("/content/drive/My Drive/model_dense121.h5")
  
val0_datagen = ImageDataGenerator(rescale=1./255)
print('2,.........',val0_datagen)
val0_generator = val0_datagen.flow_from_directory(val0_set_dir, target_size =(img_width, img_height), 
                                                  batch_size = batch_size, class_mode =None, shuffle = False) 
print('3................',val0_generator)
val0_steps_per_epoch = val0_generator.n/val0_generator.batch_size
print('4..................',val0_steps_per_epoch)

val0_generator.reset()
print('5..................',val0_generator)
predictions0 = model.predict_generator(val0_generator, steps = val0_steps_per_epoch)
print('6...................',predictions0)

predicted_classes0 = numpy.argmax(predictions0, axis=1)

################
#path to test set1
val1_set_dir = "/content/drive/My Drive/validation /set1"

num_val1 = len(os.listdir(val1_set_dir))

val1_datagen = ImageDataGenerator(rescale=1./255)

val1_generator = val1_datagen.flow_from_directory(val1_set_dir, target_size =(img_width, img_height), 
                                                  batch_size = batch_size, class_mode =None, shuffle = False) 

val1_steps_per_epoch = val1_generator.n/val1_generator.batch_size

val1_generator.reset()
predictions1 = model.predict_generator(val1_generator, steps = val1_steps_per_epoch)

predicted_classes1 = numpy.argmax(predictions1, axis=1)


####################
#path to test set2
val2_set_dir = "/content/drive/My Drive/validation /set2"

num_val2 = len(os.listdir(val2_set_dir))

val2_datagen = ImageDataGenerator(rescale=1./255)

val2_generator = val2_datagen.flow_from_directory(val2_set_dir, target_size =(img_width, img_height), 
                                                  batch_size = batch_size, class_mode =None, shuffle = False) 

val2_steps_per_epoch = val2_generator.n/val2_generator.batch_size

val2_generator.reset()
predictions2 = model.predict_generator(val2_generator, steps = val2_steps_per_epoch)

predicted_classes2 = numpy.argmax(predictions2, axis=1)

######################
#path to test set3
val3_set_dir = "/content/drive/My Drive/validation /set3"

num_val3 = len(os.listdir(val3_set_dir))
  
val3_datagen = ImageDataGenerator(rescale=1./255)

val3_generator = val3_datagen.flow_from_directory(val3_set_dir, target_size =(img_width, img_height), 
                                                  batch_size = batch_size, class_mode =None, shuffle = False) 

val3_steps_per_epoch = val3_generator.n/val3_generator.batch_size

val3_generator.reset()
predictions3 = model.predict_generator(val3_generator, steps = val3_steps_per_epoch)

predicted_classes3 = numpy.argmax(predictions3, axis=1)

##############
#path to test set4
val4_set_dir = "/content/drive/My Drive/validation /set4"

num_val4 = len(os.listdir(val4_set_dir))
  
val4_datagen = ImageDataGenerator(rescale=1./255)

val4_generator = val4_datagen.flow_from_directory(val4_set_dir, target_size =(img_width, img_height), 
                                                  batch_size = batch_size, class_mode =None, shuffle = False) 

val4_steps_per_epoch = val4_generator.n/val4_generator.batch_size

val4_generator.reset()
predictions4 = model.predict_generator(val4_generator, steps = val4_steps_per_epoch)

predicted_classes4 = numpy.argmax(predictions4, axis=1)


###################



1............ 1
2,......... <keras.preprocessing.image.ImageDataGenerator object at 0x7fd408e8d710>
Found 88 images belonging to 1 classes.
3................ <keras.preprocessing.image.DirectoryIterator object at 0x7fd3df6dc3c8>
4.................. 11.0
5.................. <keras.preprocessing.image.DirectoryIterator object at 0x7fd3df6dc3c8>
6................... [[0.1936551  0.00303189 0.3984719  0.30097395 0.10386706]
 [0.2653567  0.00666826 0.35603684 0.24495883 0.1269794 ]
 [0.24971801 0.00541071 0.3958009  0.25323883 0.09583158]
 [0.29514217 0.00254096 0.35584816 0.25974056 0.0867281 ]
 [0.2360975  0.00137827 0.34514868 0.33473963 0.08263598]
 [0.22272831 0.00095919 0.43572667 0.2659969  0.07458892]
 [0.15944654 0.00120404 0.36454213 0.37988746 0.0949199 ]
 [0.3070997  0.00338304 0.32014406 0.28901476 0.08035839]
 [0.18287541 0.00247205 0.38579503 0.3363086  0.09254896]
 [0.20936024 0.00134193 0.49204764 0.2197611  0.07748906]
 [0.17453113 0.00087525 0.39104638 0.35772747 0.075819

In [ ]:
print(type(predicted_classes0))
predictions_final=np.concatenate([predicted_classes0 , predicted_classes1 , predicted_classes2 , predicted_classes3 , predicted_classes4])
print(predictions_final.shape)
print(num_val0)
predictions_true=np.array([0 for _ in range(88)] + [1 for _ in range(77)] + [2 for _ in range(23)] + [3 for _ in range(22)] + [4 for _ in range(32)])
print(predictions_true)
print(metrics.confusion_matrix(predictions_true, predictions_final))


print(metrics.classification_report(predictions_true, predictions_final, digits=3))

<class 'numpy.ndarray'>
(242,)
1
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]
[[ 3  0 70 15  0]
 [ 0  0 71  6  0]
 [ 0  0 16  6  1]
 [ 0  0 19  3  0]
 [ 0  0 30  1  1]]
              precision    recall  f1-score   support

           0      1.000     0.034     0.066        88
           1      0.000     0.000     0.000        77
           2      0.078     0.696     0.140        23
           3      0.097     0.136     0.113        22
           4      0.500     0.031     0.059        32

    accuracy                          0.095       242
   m

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
